accelerator: gpu
accumulate_grad_batches: null
amp_backend: native
amp_level: null
arch: resnet18
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 256
benchmark: true
breeds_dataset: living17
breeds_split: rand
check_val_every_n_epoch: 1
checkpoint_callback: null
decay_epochs: 30
decay_max_epochs: 100
decay_rate: 0.1
default_root_dir: null
details: living17 Breeds dataset training
detect_anomaly: false
deterministic: true
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
evaluate: false
fast_dev_run: false
flush_logs_every_n_steps: null
gpus:
- 2
gradient_clip_algorithm: null
gradient_clip_val: null
info_dir: MISSING
inject_noise: 0.0
ipus: null
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
loss: cross_entropy
lr: 0.1
main_dir: train
max_epochs: 120
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
momentum: 0.9
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
norandomcrop: false
norandomflip: false
num_labeled_samples: 0
num_nodes: 1
num_processes: 1
num_samples_per_class: 0
num_sanity_val_steps: 2
opt: sgd
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
pretrained: false
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
root_dir: MISSING
secure_checkpoint: false
seed: 42
select_classes: []
start_epoch: 0
stochastic_weight_avg: false
strategy: dp
sync_batchnorm: false
terminate_on_nan: null
test_dir: val
tpu_cores: null
track_grad_norm: -1
val_check_interval: 1.0
weight_decay: 0.0001
weights_save_path: null
weights_summary: top
workers: 8
